### ISSUE TITLE
Add contributions.md

### ISSUE THREAD

**Issue by ChinmayMhatre** [ChinmayMhatre/TheMusicPlayer#5]

**Comment by abitsalihu** [comment]
Hey @ChinmayMhatre, I would like to help with this issue. :)

**Comment by ChinmayMhatre** [comment]
Hey @abitsalihu , you could go ahead with this. This project would be built on nextjs .

You could instruct the contributor to create an issue for any bug,feature etc then fork, clone and create a pr.
If you have any ideas we could discuss those as well.

Here are some repos you could take inspiration from.
https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/CONTRIBUTING.md
https://github.com/EddieHubCommunity/good-first-issue-finder/blob/main/CONTRIBUTING.md
